"""Initial Migration

Revision ID: e48717cf7ad8
Revises: 
Create Date: 2025-02-26 20:35:21.964506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e48717cf7ad8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('depth_sensor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('depth', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('humidity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('internal_humidity', sa.Float(), nullable=False),
    sa.Column('external_humidity', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('X', sa.Float(), nullable=False),
    sa.Column('Y', sa.Float(), nullable=False),
    sa.Column('Z', sa.Float(), nullable=False),
    sa.Column('Roll', sa.Float(), nullable=False),
    sa.Column('Pitch', sa.Float(), nullable=False),
    sa.Column('Yaw', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('X', sa.Float(), nullable=False),
    sa.Column('Y', sa.Float(), nullable=False),
    sa.Column('Z', sa.Float(), nullable=False),
    sa.Column('Roll', sa.Float(), nullable=False),
    sa.Column('Pitch', sa.Float(), nullable=False),
    sa.Column('Yaw', sa.Float(), nullable=False),
    sa.Column('Arm', sa.Boolean(), nullable=False),
    sa.Column('Hover', sa.Boolean(), nullable=False),
    sa.Column('S1', sa.Integer(), nullable=False),
    sa.Column('S2', sa.Integer(), nullable=False),
    sa.Column('S3', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leak_detection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('leak_detected', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('motors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('M1', sa.Integer(), nullable=False),
    sa.Column('M2', sa.Integer(), nullable=False),
    sa.Column('M3', sa.Integer(), nullable=False),
    sa.Column('M4', sa.Integer(), nullable=False),
    sa.Column('M5', sa.Integer(), nullable=False),
    sa.Column('M6', sa.Integer(), nullable=False),
    sa.Column('M7', sa.Integer(), nullable=False),
    sa.Column('M8', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pressure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('internal_pressure', sa.Float(), nullable=False),
    sa.Column('external_pressure', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('S1', sa.Integer(), nullable=False),
    sa.Column('S2', sa.Integer(), nullable=False),
    sa.Column('S3', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sonar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('sonar_data', sa.PickleType(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('temperature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('internal_temp', sa.Float(), nullable=False),
    sa.Column('external_temp', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voltage_current',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('voltage1', sa.Float(), nullable=False),
    sa.Column('voltage2', sa.Float(), nullable=False),
    sa.Column('voltage3', sa.Float(), nullable=False),
    sa.Column('current1', sa.Float(), nullable=False),
    sa.Column('current2', sa.Float(), nullable=False),
    sa.Column('current3', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voltage_current')
    op.drop_table('temperature')
    op.drop_table('sonar')
    op.drop_table('servos')
    op.drop_table('pressure')
    op.drop_table('motors')
    op.drop_table('leak_detection')
    op.drop_table('inputs')
    op.drop_table('imu')
    op.drop_table('humidity')
    op.drop_table('depth_sensor')
    # ### end Alembic commands ###
